# General info
title: My blog
author: 
  name: Manuel
  email: manuelcitarella99@gmail.com
description: My writings
url: "https://manuelcitarella.github.io/"
baseurl: "/Manucit.dev"

theme: minima

kramdown:
  input: GFM 
  syntax_highlighter: rouge 

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
