# General info
title: Manuelito dev writings
description: My writings
baseurl: "/Manucit.dev"

collections:
  projects:
    output: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
